### PR TITLE
change default icon size for small buttons

### PR DESCRIPTION
**Pull request by annekao**

### CODE REVIEW

**Review by CrookedGrin — COMMENTED** [review]
Hey, Anne! Thanks for making this PR. I'm happy to pull this in, but it's also possible to make the change directly within the button itself. We're planning to eventually migrate all these override styles into the actual CSS of the library. The overrides were initially necessary before we had our own fork of Shoelace that we could edit directly.

If you need this sooner rather than later, LMK and we can just pull this in now.

**Comment by annekao** [comment]
made the change! @CrookedGrin

**Review by CrookedGrin — APPROVED** [review]
LGTM! I'll pull these in and cut a new release. Thanks!

**Review by CrookedGrin — CHANGES_REQUESTED** [review]
Actually, looks like you need to run `prettier`

**Pull request merged**
